### ISSUE TITLE
allow to have multiple roots with combined unique index

### ISSUE THREAD

**Issue by macrozone** [adamjkb/bark#96]
this is basically a continuation from https://github.com/adamjkb/bark/issues/89 as I have the same situation.

solution would be to optionally be able to declare a combined index that has to contain `path`

e.g. 

`@@unique([tenantId, path])`

bark would need to know that, so each call that uses a path would need to know the other properties that make up that key (here: {tenantId})`

With multiple properties

`@@unique([a, b, c, ..., path])` it would need an additional ({a, b, c, ... }) identifier  an all calls. With no extra keys, we are back at the special case that is supported now (were path itself is unique)  and the additional identifier is empty.

when initializing bark, you would need to pass the name of that index (which in example a is `tenantId_path`). this is also the property that prisma generates.

this probably needs some refactoring, but should be straight forward otherwise and would open up bark for many more usecases.

**Comment by adamjkb** [comment]
I believe the same solution applies to this issue as well. What you probably want to do is create a root for each tenant instead of mantaining seperate paths per tree. 

While I think it is technically possible to achieve it might involve a lot more refactoring then it seems at first glance. Finding nodes for a lot of operations becomes a lot harder once the `path` isn't unique anymore.
